### ISSUE TITLE
The Cooling Tower crash

### ISSUE THREAD

**Issue by TPC25** [tgstyle/MCT-Immersive-Technology#206]
Got a crash the moment I use the hammer to create it. It will form into the tower then in one second, it crash the game.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  B3M_CorePlugin (B3M-1.12.2-15.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.2.280.jar)
  GSHooksLoader (GalaxySpace-1.12.2-2.0.14.jar)
Contact their authors BEFORE contacting forge

// But it works on my machine.

Time: 11/20/20 6:39 PM
Description: Unexpected error

java.lang.ArrayIndexOutOfBoundsException: -1
	at mctmods.immersivetechnology.common.util.multiblock.MultiblockUtils.GetItemStack(MultiblockUtils.java:105)
	at mctmods.immersivetechnology.common.blocks.metal.tileentities.TileEntityCoolingTowerSlave.getOriginalBlock(TileEntityCoolingTowerSlave.java:189)
	at mctmods.immersivetechnology.common.blocks.BlockITMultiblock.getOriginalBlock(BlockITMultiblock.java:76)
	at mctmods.immersivetechnology.common.blocks.BlockITMultiblock.getPickBlock(BlockITMultiblock.java:68)
	at jobicade.betterhud.element.BlockViewer.getDisplayStack(BlockViewer.java:167)
	at jobicade.betterhud.element.BlockViewer.shouldRender(BlockViewer.java:103)
	at jobicade.betterhud.element.HudElement.tryRender(HudElement.java:260)
	at jobicade.betterhud.element.HudElement.renderAll(HudElement.java:279)
	at jobicade.betterhud.events.RenderEvents.renderOverlay(RenderEvents.java:140)
	at jobicade.betterhud.events.RenderEvents.onRenderTick(RenderEvents.java:56)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_658_RenderEvents_onRenderTick_Pre.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.client.GuiIngameForge.pre(GuiIngameForge.java:907)
	at net.minecraftforge.client.GuiIngameForge.func_175180_a(GuiIngameForge.java:119)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1098)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Kurtchekov** [comment]
[MCTImmersiveTechnology-1.12.2-1.8.87.jar.zip](https://github.com/tgstyle/MCT-Immersive-Technology/files/5576702/MCTImmersiveTechnology-1.12.2-1.8.87.jar.zip)
Try this one jar, please, and let me know if it fixes the problem

**Comment by TPC25** [comment]
I have tested it out, it's working good now. Runs smooth.

**Comment by Kurtchekov** [comment]
Thanks, will be updating the mod soon
