### ISSUE TITLE
The liquid name of "hot spring water "is conflict with Sakura mod.

### ISSUE THREAD

**Issue by PilyziFox** [tgstyle/MCT-Immersive-Technology#251]
[Sakura mod](https://www.curseforge.com/minecraft/mc-mods/sakura) 
Hello,
When I update "IT" to the latest version, the original "hot spring water" belong to Sakura mod was turn into this mod own and also lost the ability it had had. 
And when I interact with it using the bucket,the game crash and leave the following report:

Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraftforge.fluids.FluidStack.getFluid(FluidStack.java:119)
	at net.minecraftforge.fluids.FluidStack.copy(FluidStack.java:137)
	at net.minecraftforge.fluids.BlockFluidClassic.drain(BlockFluidClassic.java:333)
	at net.minecraftforge.fluids.capability.wrappers.FluidBlockWrapper.drain(FluidBlockWrapper.java:107)
	at net.minecraftforge.fluids.FluidUtil.tryFluidTransfer(FluidUtil.java:409)
	at net.minecraftforge.fluids.FluidUtil.tryFillContainer(FluidUtil.java:139)
	at net.minecraftforge.fluids.FluidUtil.tryPickUpFluid(FluidUtil.java:573)
	at net.minecraftforge.fluids.UniversalBucket.onFillBucket(UniversalBucket.java:243)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1085_UniversalBucket_onFillBucket_FillBucketEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onBucketUse(ForgeEventFactory.java:469)
	at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:43)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:511)
	at net.optifine.override.PlayerControllerOF.func_187101_a(PlayerControllerOF.java:80)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1597)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraftforge.fluids.FluidStack.getFluid(FluidStack.java:119)
	at net.minecraftforge.fluids.FluidStack.copy(FluidStack.java:137)
	at net.minecraftforge.fluids.BlockFluidClassic.drain(BlockFluidClassic.java:333)
	at net.minecraftforge.fluids.capability.wrappers.FluidBlockWrapper.drain(FluidBlockWrapper.java:107)
	at net.minecraftforge.fluids.FluidUtil.tryFluidTransfer(FluidUtil.java:409)
	at net.minecraftforge.fluids.FluidUtil.tryFillContainer(FluidUtil.java:139)
	at net.minecraftforge.fluids.FluidUtil.tryPickUpFluid(FluidUtil.java:573)
	at net.minecraftforge.fluids.UniversalBucket.onFillBucket(UniversalBucket.java:243)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1085_UniversalBucket_onFillBucket_FillBucketEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at com.github.terminatornl.laggoggles.tickcentral.EventBusTransformer.redirectEvent(EventBusTransformer.java:67)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onBucketUse(ForgeEventFactory.java:469)
	at net.minecraft.item.ItemBucket.func_77659_a(ItemBucket.java:43)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:511)
	at net.optifine.override.PlayerControllerOF.func_187101_a(PlayerControllerOF.java:80)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1597)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

**Comment by Ironnoob73** [comment]
The same thing happened when installed with BOP.

**Comment by tgstyle** [comment]
This will not be fixed, the mod is unsupported.
